# Generated by Django 4.2.4 on 2023-10-27 12:31

from django.db import migrations, models
import django.db.models.deletion
import mail_master_app.validator
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('memberplatform_id', models.UUIDField(blank=True, null=True)),
                ('platform_id', models.UUIDField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('api_credentials_file', models.FileField(null=True, upload_to='credentials/api_credentials_file/', validators=[mail_master_app.validator.validate_json_extension])),
                ('api_credentials_text', models.JSONField(default=dict, null=True)),
                ('credentials_file', models.FileField(null=True, upload_to='credentials/credentials_file/')),
                ('credentials_text', models.JSONField(default=dict, null=True)),
                ('image', models.ImageField(null=True, upload_to='credentials/image/', validators=[mail_master_app.validator.validate_image_extension])),
                ('status', models.PositiveIntegerField(default=0)),
                ('created_by', models.UUIDField(null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachments', models.FileField(null=True, upload_to='mail_deatails/attachments/', validators=[mail_master_app.validator.validate_image_pdf_extension])),
                ('created_by', models.UUIDField(null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailDeatail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('memberplatform_id', models.UUIDField(blank=True, null=True)),
                ('platform_id', models.UUIDField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_page_text', models.TextField(blank=True, null=True)),
                ('html_page_to_pdf_content', models.TextField(blank=True, null=True)),
                ('html_page_to_pdf_url', models.TextField(blank=True, null=True)),
                ('html_convertion_type', models.CharField(blank=True, choices=[('PDF', 'HTML TO PDF'), ('JPG', 'HTML TO JPG'), ('JPEG', 'HTML TO JPEG')], default='PDF', max_length=256, null=True)),
                ('variables', models.JSONField(blank=True, null=True)),
                ('recipient_sheets', models.FileField(null=True, upload_to='mail_deatails/recipient_sheets/', validators=[mail_master_app.validator.validate_recipient_extension])),
                ('delay', models.IntegerField(default=0, null=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('send_counts', models.IntegerField(default=50, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.UUIDField(null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='mail_deatail_attachments', to='mail_master_app.mailattachment')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_credential', to='mail_master_app.credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('memberplatform_id', models.UUIDField(blank=True, null=True)),
                ('platform_id', models.UUIDField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_page_text', models.TextField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField(null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('memberplatform_id', models.UUIDField(blank=True, null=True)),
                ('platform_id', models.UUIDField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('recipient_list', models.JSONField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('success_list', models.JSONField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('failure_list', models.JSONField(blank=True, null=True)),
                ('tacking_deatails', models.JSONField(blank=True, null=True)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_deatail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_deatail', to='mail_master_app.maildeatail')),
            ],
        ),
    ]
