# Generated by Django 4.2.4 on 2023-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_master_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maildeatail',
            old_name='variables',
            new_name='convertions_variables',
        ),
        migrations.RemoveField(
            model_name='maildeatail',
            name='html_page_to_pdf_url',
        ),
        migrations.AddField(
            model_name='maildeatail',
            name='from_alias',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='maildeatail',
            name='html_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildeatail',
            name='other_variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
